import os

ROOT_CERTIFICATE =  os.environ.get("FLINK_REST_API_ROOT_CERTIFICATE")
BASIC_AUTHENTICATION_USERNAME =  os.environ.get("FLINK_REST_API_BASIC_AUTH_USERNAME")
BASIC_AUTHENTICATION_PASSWORD =  os.environ.get("FLINK_REST_API_BASIC_AUTH_PASSWORD")